project:
  type: website
  output-dir: docs
  resources:
    - googleb8ecb1c6982be639.html

website:
  title: "Yun-Ting Yeh"
  site-url: https://ytyeh.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
  page-footer: 
    right: "Last updated: July 14, 2025" 
    left:
      - icon: github
        href: https://github.com/ytyeh/ytyeh.github.io
  open-graph: 
    title: "Yun-Ting Yeh | PhD Candidate in Environmental Econ & IO"
    image: "images/pic_horizontal.png"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    fontsize: 1.1em
    linestretch: 1.7
    css:
      - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    toc: true
    description-meta: "PhD candidate in environmental economics and industrial organization at the University of Arizona."
    
editor: visual

execute:
  freeze: auto




